### ISSUE TITLE
[Rails 3?] `timber install` sets up log level incorrectly, causing boot exception

### ISSUE THREAD

**Issue by bjeanes** [timberio/timber-ruby#98]
I meant to open this issue last week, but figured it out and forgot about it. I'm currently experimenting with a change to timber (<strike>which I'll PR if it bears fruit</strike>#99) so ran into it again.

Exception (e.g. from running `rake middleware`):

```
ArgumentError: comparison of Fixnum with :debug failed
/Users/bjeanes/Code/timber-ruby/lib/timber/logger.rb:244:in `<'
/Users/bjeanes/Code/timber-ruby/lib/timber/logger.rb:244:in `add'
/Users/bjeanes/Code/timber-ruby/lib/timber/logger.rb:259:in `info'
/Users/bjeanes/.gem/ruby/2.2.6/gems/activerecord-3.2.22.5/lib/active_record/railtie.rb:86:in `block (2 levels) in <class:Railtie>'
/Users/bjeanes/.gem/ruby/2.2.6/gems/activesupport-3.2.22.5/lib/active_support/lazy_load_hooks.rb:36:in `instance_eval'
/Users/bjeanes/.gem/ruby/2.2.6/gems/activesupport-3.2.22.5/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
/Users/bjeanes/.gem/ruby/2.2.6/gems/activesupport-3.2.22.5/lib/active_support/lazy_load_hooks.rb:26:in `block in on_load'
/Users/bjeanes/.gem/ruby/2.2.6/gems/activesupport-3.2.22.5/lib/active_support/lazy_load_hooks.rb:25:in `each'
/Users/bjeanes/.gem/ruby/2.2.6/gems/activesupport-3.2.22.5/lib/active_support/lazy_load_hooks.rb:25:in `on_load'
/Users/bjeanes/.gem/ruby/2.2.6/gems/activerecord-3.2.22.5/lib/active_record/railtie.rb:80:in `block in <class:Railtie>'
/Users/bjeanes/.gem/ruby/2.2.6/gems/railties-3.2.22.5/lib/rails/initializable.rb:30:in `instance_exec'
/Users/bjeanes/.gem/ruby/2.2.6/gems/railties-3.2.22.5/lib/rails/initializable.rb:30:in `run'
/Users/bjeanes/.gem/ruby/2.2.6/gems/railties-3.2.22.5/lib/rails/initializable.rb:55:in `block in run_initializers'
/Users/bjeanes/.gem/ruby/2.2.6/gems/railties-3.2.22.5/lib/rails/initializable.rb:54:in `each'
/Users/bjeanes/.gem/ruby/2.2.6/gems/railties-3.2.22.5/lib/rails/initializable.rb:54:in `run_initializers'
/Users/bjeanes/.gem/ruby/2.2.6/gems/railties-3.2.22.5/lib/rails/application.rb:136:in `initialize!'
/Users/bjeanes/.gem/ruby/2.2.6/gems/railties-3.2.22.5/lib/rails/railtie/configurable.rb:30:in `method_missing'
/Users/bjeanes/Code/timber-test/config/environment.rb:5:in `<top (required)>'
/Users/bjeanes/.gem/ruby/2.2.6/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `require'
/Users/bjeanes/.gem/ruby/2.2.6/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `block in require'
/Users/bjeanes/.gem/ruby/2.2.6/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:236:in `load_dependency'
/Users/bjeanes/.gem/ruby/2.2.6/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `require'
/Users/bjeanes/.gem/ruby/2.2.6/gems/railties-3.2.22.5/lib/rails/application.rb:103:in `require_environment!'
/Users/bjeanes/.gem/ruby/2.2.6/gems/railties-3.2.22.5/lib/rails/application.rb:305:in `block (2 levels) in initialize_tasks'
/Users/bjeanes/.gem/ruby/2.2.6/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/Users/bjeanes/.gem/ruby/2.2.6/gems/bundler-1.14.4/lib/bundler/cli/exec.rb:74:in `load'
/Users/bjeanes/.gem/ruby/2.2.6/gems/bundler-1.14.4/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Users/bjeanes/.gem/ruby/2.2.6/gems/bundler-1.14.4/lib/bundler/cli/exec.rb:27:in `run'
/Users/bjeanes/.gem/ruby/2.2.6/gems/bundler-1.14.4/lib/bundler/cli.rb:335:in `exec'
/Users/bjeanes/.gem/ruby/2.2.6/gems/bundler-1.14.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/bjeanes/.gem/ruby/2.2.6/gems/bundler-1.14.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/bjeanes/.gem/ruby/2.2.6/gems/bundler-1.14.4/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/Users/bjeanes/.gem/ruby/2.2.6/gems/bundler-1.14.4/lib/bundler/cli.rb:20:in `dispatch'
/Users/bjeanes/.gem/ruby/2.2.6/gems/bundler-1.14.4/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/Users/bjeanes/.gem/ruby/2.2.6/gems/bundler-1.14.4/lib/bundler/cli.rb:11:in `start'
/Users/bjeanes/.gem/ruby/2.2.6/gems/bundler-1.14.4/exe/bundle:32:in `block in <top (required)>'
/Users/bjeanes/.gem/ruby/2.2.6/gems/bundler-1.14.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/Users/bjeanes/.gem/ruby/2.2.6/gems/bundler-1.14.4/exe/bundle:24:in `<top (required)>'
/Users/bjeanes/.gem/ruby/2.2.6/bin/bundle:23:in `load'
/Users/bjeanes/.gem/ruby/2.2.6/bin/bundle:23:in `<main>'
Tasks: TOP => middleware => environment
```

This seems to be because (at least in Rails 3), `config.log_level` is a Symbol such as `:debug`, but `Logger#level=` (and by extension, `Timber::Logger#level=` expects a Fixnum (usually by way of `Logger::DEBUG #=> 0`, et al).

**Comment by binarylogic** [comment]
Good catch, we need to update the initializer code. [Here's what Rails does](https://github.com/rails/rails/blob/827bfe4f41c39eade078e26ad5653979891d89c7/railties/lib/rails/application/bootstrap.rb#L59). I'm not entirely sure why they mess with a symbol. My guess is to ensure the constant pulled is from the logger being used. If you add this immediately after instantiating the `Timber::Logger` you should be good to go:

```ruby
logger = Timber::Logger.const_get(config.log_level.to_s.upcase)
```

I'm also going to update the `Timber::Logger` to take a Symbol for `#level=`.
